### ISSUE TITLE
Is this a 64-bit or 32-bit version?

### ISSUE THREAD

**Issue by Vitae666** [nls0/C-Hero-Calc#1]
Asking because I've had some crashes happen out of the blue like I did with the old 32-bit version.

**Comment by nls0** [comment]
64-bit.

**Comment by Vitae666** [comment]
Thanks. I do see it using less memory. Not sure why the crashing tho. It's not as often as with the old 32bit versions, but I didn't have any crashes with the 64's before. Aw well :)
