### ISSUE TITLE
Request for an output change

### ISSUE THREAD

**Issue by Vitae666** [nls0/C-Hero-Calc#5]
Silly question, but was there a reason for the cost to the game to put up the Monsters to be there? Does it really matter to us, the players, what the cost is? 
I'd meant to ask back when Dice was doing the Calc, but honestly, once the GUI came around, I forgot all about it because I hardly ever had a reason to run the Calc in raw format.

Any reason it can't just be:
Solution for [quest92-3 | Followers: e16 a17 w17 a18 a18 f17 <==]:
?

**Comment by nls0** [comment]
It can be useful to some people to get a rough idea of how strong the enemy lineup is maybe.

**Comment by Vitae666** [comment]
Hrmm. Ok. I mean, I beat a lineup 2.5x my followers...
But if it is useful to others, no worries :)

**Comment by GizmoMar** [comment]
It is extremely useful for me in other types of calculations where I need to know how strong the lane is. Highly recommend it stays.
